version: '3.8'
services:

  redis:
    image: redis:latest
    container_name: redis_container
    # ports:
    #   - 6379:6379

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - DB_NAME = postgres
      - DB_USER = postgres
      - DB_PASSWORD = postgres

    container_name: postgres_db

  app:
    build: .
    volumes:
      - .:/django_api
    ports:
      - 8000:8000
    image: app:django_api
    container_name: django_api_container
    # command: python manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    
  celery:
    restart: always
    build: 
      context: .
    command: celery -A django_api worker --loglevel=DEBUG
    volumes:
      - .:/django_api
    container_name: celery_container
    depends_on:
      - db
      - redis
      - app 
